version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
      commands:
      - echo "install"
    pre_build:
      commands:
      - echo "Entered the pre-build phase"
    build:
      commands:      
      - mvn package
      - echo "Entered build phase"
    post_build:
      commands:
      - echo "Entered the post-build phase"
artifacts:
  files:
    - target\demoaws-0.0.1-SNAPSHOT.jar